<?php

/**
 * @file
 * UI Patterns Field Formatters module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function ui_patterns_field_formatters_help($route_name, RouteMatchInterface $arg) {
  switch ($route_name) {
    case 'help.page.ui_patterns_field_formatters':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The UI Patterns Field Formatters module exposes components from UI Patterns to the Field Formatter API.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function ui_patterns_field_formatters_field_formatter_info_alter(array &$info) {
  /** @var \Drupal\Core\Field\FieldTypePluginManagerInterface $field_type_manager */
  $field_type_manager = \Drupal::service('plugin.manager.field.field_type');
  $field_types = array_keys($field_type_manager->getDefinitions());

  $info['pattern_all_formatter']['field_types'] = $field_types;
  $info['pattern_each_formatter']['field_types'] = $field_types;
}
